parameters:
  hot.tracking_bundle.default_app_name: unknown
  hot.tracking_bundle.default_app_component: unknown
  hot.tracking_bundle.applicationName: '%env(default:hot.tracking_bundle.default_app_name:METRICS_APPLICATION_NAME)%'
  hot.tracking_bundle.componentName: '%env(default:hot.tracking_bundle.default_app_component:METRICS_COMPONENT_NAME)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $applicationName: '%hot.tracking_bundle.applicationName%'
      $componentName: '%hot.tracking_bundle.componentName%'

  Hot\TracingBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Messenger/Middleware'
      - '../../TracingBundle.php'

  Hot\TracingBundle\Messenger\Middleware\:
    resource: '../../Messenger/Middleware'
    tags:
      - name: 'messenger.middleware'
